version: '3.4'

services:
  php:
    container_name: larafony-php
    tty: true
    build:
      context: ./
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html

  database:
    image: 'mariadb:latest'
    container_name: larafony-database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: larafony
    ports:
      - '3306:3306'

  nginx:
    container_name: larafony-nginx
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf